### ISSUE TITLE
Add Github integration

### ISSUE THREAD

**Issue by overeha** [code4romania/data-portal#11]
The Get Involved section must automatically drag tasks from dedicated github repositories. 
The View all cleaning tasks link should direct the user to the Cleaning tasks repo dedicated to that specific portal 

See section above footer here: 
![homepage cluj-napoca](https://user-images.githubusercontent.com/45068169/51712477-864d1700-2037-11e9-8adf-b56a52f7e031.png)

**Comment by mihaela94** [comment]
Ma ocup eu de asta.
