### ISSUE TITLE
Create Categories bar

### ISSUE THREAD

**Issue by overeha** [code4romania/data-portal#13]
The Categories bar is a horizontal listing of all categories:
- each category has an icon and a title
![recycling 1 e](https://user-images.githubusercontent.com/45068169/51790163-4ce0ec80-219a-11e9-8830-58a81af1b437.png)
![recycling](https://user-images.githubusercontent.com/45068169/51790164-4ce0ec80-219a-11e9-8acf-e46a6dfede97.png)

![save-water 1 e](https://user-images.githubusercontent.com/45068169/51787903-f9fa3b80-217f-11e9-8487-c16a5f9aa975.png)
![save-water](https://user-images.githubusercontent.com/45068169/51787904-f9fa3b80-217f-11e9-9f37-510e38af7b28.png)
![ambulance 1 e](https://user-images.githubusercontent.com/45068169/51787905-f9fa3b80-217f-11e9-8fa0-34a3153d8e4c.png)
![ambulance](https://user-images.githubusercontent.com/45068169/51787906-fa92d200-217f-11e9-8d8b-c6daaab16022.png)
![building 1 e](https://user-images.githubusercontent.com/45068169/51787907-fa92d200-217f-11e9-96ea-d083204a5031.png)
![building](https://user-images.githubusercontent.com/45068169/51787908-fa92d200-217f-11e9-93a4-cb0fbf1119b4.png)
![bus 1 e](https://user-images.githubusercontent.com/45068169/51787909-fa92d200-217f-11e9-9c3e-1d3d2dd547e7.png)
![bus](https://user-images.githubusercontent.com/45068169/51787910-fb2b6880-217f-11e9-841b-251921ac250a.png)
![citizen 1 e](https://user-images.githubusercontent.com/45068169/51787911-fb2b6880-217f-11e9-8a93-893d40cae066.png)
![citizen](https://user-images.githubusercontent.com/45068169/51787912-fb2b6880-217f-11e9-8da7-53737c3aa045.png)
![university 1](https://user-images.githubusercontent.com/45068169/51787945-65440d80-2180-11e9-974c-d8d52a2ade3c.png)
![university](https://user-images.githubusercontent.com/45068169/51787946-65440d80-2180-11e9-9900-955811d7b40c.png)
![electric-car 1 e](https://user-images.githubusercontent.com/45068169/51787914-fbc3ff00-217f-11e9-83b9-e8c825a614b7.png)
![electric-car](https://user-images.githubusercontent.com/45068169/51787915-fbc3ff00-217f-11e9-9994-593dbf18fdc1.png)
![recycling](https://user-images.githubusercontent.com/45068169/51787916-fbc3ff00-217f-11e9-81d7-5051fde18085.png)

See wireframes example here
![homepage cluj-napoca](https://user-images.githubusercontent.com/45068169/51713143-b8f80f00-2039-11e9-98d9-a886f39a1863.png)
![home local overlay 1](https://user-images.githubusercontent.com/45068169/51713151-bd242c80-2039-11e9-8393-a72b78a401a8.png)

Style:
- background: #21409A
- font: Titilium Web Semibold, 12px, color: #ffffff
- on hover, each category will 
    - display a #FFDE17 background, 
    - icon changes color to #000000, 
    - text changes color to #000000
- if selected each category will
    - display a #FFDE17 background, 
    - icon changes color to #000000, 
    - text changes color to #000000

**Comment by surdu** [comment]
Mabe a good task for this issue would be to create a way to populate the database with the necessary categories.

**Comment by costibleotu** [comment]
@surdu follow https://github.com/code4romania/ckanext-dataportaltheme/issues/27 :)

**Comment by costibleotu** [comment]
@ancaspatariu - poti sa faci tu, te rog, background-ul din spatele icoanelor `#21409A`?
![image](https://user-images.githubusercontent.com/1089585/52680721-32e92d00-2f42-11e9-930c-2ac59e69bd93.png)

**Comment by ancaspatariu** [comment]
@costibleotu - sure, ma ocup.

**Comment by ancaspatariu** [comment]
<img width="1438" alt="screenshot 2019-02-13 at 23 32 05" src="https://user-images.githubusercontent.com/14015654/52745995-3257a180-2fe9-11e9-99c6-2c6a54d6a547.png">
Done. Am mai facut cateva modficari sa fie ca-n design.
