### ISSUE TITLE
Research ckan-harvest

### ISSUE THREAD

**Issue by overeha** [code4romania/data-portal#16]

**Comment by costibleotu** [comment]
We should research this extension ( is the most used extension for harvesting data from different sources) and see how we can use it to gather data from different sources ( mysql, google spreadsheets, and more..)

You can start from here: 
https://github.com/ckan/ckanext-harvest

:)

**Comment by boldisteanu** [comment]
By following the installation steps I was able to configure the harvester to run manually and via the supervisor to fetch dataset definitions by just supplying the domain URL of an external CKAN instance.

Please note that the harvester only imports dataset definitions from other CKAN instances, it does not import directly from other DBs, files, etc.

I suggest as a next step to modify the vagrant environment to configure and activate the harvester and supervisor.

**Comment by iurab** [comment]
Importing data sets from other CKAN instances is the default feature of  `ckanext-harvest`.
With it, we can build other extensions that can import, I suppose, any type of data.
For example there is https://github.com/ckan/ckanext-dcat, which can import RDF, XML and JSON types.
