### ISSUE TITLE
Implement Data Portal Theme

### ISSUE THREAD

**Issue by overeha** [code4romania/data-portal#17]
- [ ] footer.css
- [ ] social.css
- [ ] social.html
- [ ] header.css 
- [ ] categories.css
- [ ] categories.html

**Comment by boldisteanu** [comment]
Should this be a milestone rather than an issue?

**Comment by costibleotu** [comment]
@boldisteanu - indeed

**Comment by boldisteanu** [comment]
Milestone created. Closing this issue.
