### ISSUE TITLE
Create Icon set for Data Portal

### ISSUE THREAD

**Issue by overeha** [code4romania/data-portal#19]
Create an icon set for the Categories bar in Data Portal 
See categories here in the wireframe
![dataset page](https://user-images.githubusercontent.com/45068169/51784651-d968bc00-2154-11e9-8be2-516753cc1c3c.png)

**Comment by costibleotu** [comment]
@overeha `Cultura` nu ar trebui sa fie o categorie? :)

**Comment by costibleotu** [comment]
Si ne trebuie icoanele pe alb
